### ISSUE TITLE
Compute the byte size of constant-sized data types

### ISSUE THREAD

**Issue by tahina-pro** [project-everest/quackyducky#4]
In the TLS RFC and others, arrays are specified with bounds on their size representation in bytes. However, we want to specify and implement parsers and serializers for arrays as lists with refinements based on bounds on the number of elements instead.
Thus, we would need QuackyDucky to compute those bounds and output them as numerical constants as `elem_count*` arguments to the combinators in `LowParse.*.Array` (in addition to the `array_byte_size*` arguments, which should be filled in with the byte size bounds directly from the RFC.)
Example coming soon.

**Comment by ad-l** [comment]
This is fully implemented now
